blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/nahyeongjin1/NHJ.log/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ê°€ ìˆë‹¤ë©´ Discussionì„ ì´ìš©í•´ì£¼ì„¸ìš”
  - name: ğŸ“– Wiki
    url: https://github.com/nahyeongjin1/NHJ.log/wiki
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œëŠ” Wikië¥¼ ì°¸ê³ í•´ì£¼ì„¸ìš”
